spring:
  servlet:
    multipart:
       #配置允许上传的文件大小
       max-file-size: 100MB
       max-request-size: 1000MB
  cache:
    #集群推荐使用redis缓存，单机可以使用simple本地缓存缓存
    type: simple
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8 #日期序列化走北京时间
  main.allow-bean-definition-overriding: true
server:
  port: 8181